version: '3.7'
services:
  geeks_db:
    build:
      dockerfile: ./Dockerfile_geeks_db
      context: ./geeks_db
    image: geeks_db
    container_name: geeks_db_c1
    networks:
      - internal_network
    volumes:
      - ./geeks_db:/docker-entrypoint-initdb.d/
      - ./geeks_db_data:/var/lib/postgresql/data
      - ./db_backups:/db_backups
    ports:
      - '5433:5432'
    expose: [5432]

  geeks_server:
    build:
      dockerfile: Dockerfile_geeks_server
      context: ./geeks_server
    image: geeks_server
    container_name: geeks_server_c1
    networks:
      - internal_network
    working_dir: /geeks_server
    command: >
      flask run --host=0.0.0.0 --port=8000

    volumes:
      - ./geeks_server:/geeks_server
    env_file:
      - config.env
    ports:
      - '8000:8000'
networks:
  internal_network:
    driver: bridge
