version: '3.7'
services:
  geeks_db:
    build:
      dockerfile: ./Dockerfile_geeks_db
      context: ./geeks_db
    image: geeks_db
    container_name: geeks_db_c1
    networks:
      - internal_network
    volumes:
      - ./geeks_db:/docker-entrypoint-initdb.d/
      - ./geeks_db_data:/var/lib/postgresql/data
      - ./db_backups:/db_backups
    ports:
      - '5433:5432'
    expose: [5432]

  geeks_server:
    build:
      dockerfile: Dockerfile_geeks_server
      context: ./geeks_server
    image: geeks_server
    container_name: geeks_server_c1
    networks:
      - internal_network
    working_dir: /geeks_server
    command: >
      flask run --host=0.0.0.0 --port=8000

    volumes:
      - ./geeks_server:/geeks_server
    env_file:
      - config.env
    ports:
      - '8000:8000'
#  geeks_jenkins:
#    image: jenkins/jenkins:lts
#    privileged: true
#    user: root
#    ports:
#      - 8081:8080
#      - 50000:50000
#    container_name: jenkins
#    volumes:
#      - ~/jenkins:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/local/bin/docker:/usr/local/bin/docker
  geeks_flask:
      build:
        dockerfile: Dockerfile_flask
        context: ./geeks_server
      volumes:
        - ./geeks_server:/geeks_server
      networks:
        - internal_network
      ports:
        - 5000:5000
  react-app:
    build:
      context: ../geeks-for-geeks-ui/prior-knowledge-survey-ui
      dockerfile: Dockerfile
    volumes:
      - ../../geeks-for-geeks-ui/prior-knowledge-survey-ui:/app
    networks:
      - internal_network
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    expose: [3000]

networks:
  internal_network:
    driver: bridge

